GET http://localhost:5000/api/game

###

POST http://localhost:5000/api/game HTTP/1.1
content-type: application/json

{
    "HitStick": "Stick"
}

###
POST http://localhost:5222/api/reset HTTP/1.1
content-type: application/json

{
    "seed": "42"
}

###
POST http://localhost:5222/api/step HTTP/1.1
content-type: application/json

{
    "action": "1"
}