GET http://localhost:5000/api/game

###

POST http://localhost:5000/api/game HTTP/1.1
content-type: application/json

{
    "HitStick": "Stick"
}

###
POST https://bvme.azurewebsites.net/api/reset HTTP/1.1
content-type: application/json

{
    "playerId": "asdf",
    "seed" : "42",
    "action": "1"
}

###
POST http://localhost:5222/api/step HTTP/1.1
content-type: application/json

{
    "seed" : "1",
    "action": "1"
}